import argparse
import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from sea_surface_lightning.config import ensure_project_dirs, load_config
from sea_surface_lightning.plotting import load_rollout_mat, save_rollout_plots



def parse_args():
    parser = argparse.ArgumentParser(description="Replot rollout MAT results.")
    parser.add_argument("--config", type=str, required=True, help="Path to YAML config.")
    parser.add_argument("--mat", type=str, required=True, help="MAT file path generated by validate.py/test.py.")
    parser.add_argument("--split", type=str, default="custom", help="Output subdir name.")
    return parser.parse_args()



def main() -> None:
    args = parse_args()
    cfg = load_config(args.config)
    ensure_project_dirs(cfg)
    data = load_rollout_mat(args.mat)
    save_dir = os.path.join(cfg["paths"]["plot_dir"], args.split)
    save_rollout_plots(data, save_dir, cfg)
    print(f"Saved plots to: {save_dir}")


if __name__ == "__main__":
    main()
